version: 0.2

phases:
  post_build:
    commands:
      - echo Creating directories for output
      - mkdir -p $CODEBUILD_SRC_DIR/output/
      - echo Moving files
      - ls -la
      - rm -rf infra.yml buildspec.yml .gitignore
      - echo Sync S3 bucket
      - aws s3 sync $CODEBUILD_SRC_DIR/ s3://${BUCKET_NAME} --acl=public-read --delete
      - echo Create invalidation
      - aws cloudfront create-invalidation --distribution-id ${DISCTRIBUTION_ID} --paths /
