# Simple workflow for deploying testing
name: Test code for RP

on:
  # Runs on PR for all branch
  pull_request:
    branches: ["dev"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: list folder
        run: ls -la
        
      - name: fail
        run: exit 1
